# Generated by Django 5.1.7 on 2025-04-07 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_app', '0010_alter_college_fee_structure'),
        ('collages', '0002_alter_courses_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['name'], 'verbose_name': 'College Course', 'verbose_name_plural': 'College Courses'},
        ),
        migrations.RemoveField(
            model_name='courses',
            name='collage',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='price',
        ),
        migrations.AddField(
            model_name='courses',
            name='college',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='college_courses', to='admission_app.college'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='duration_years',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Course duration in years (e.g., 3, 2.5)', max_digits=3),
        ),
        migrations.AddField(
            model_name='courses',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Course fee in INR', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/images/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, help_text='Is the course currently active?', null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='level',
            field=models.CharField(choices=[('ug', 'Undergraduate'), ('pg', 'Postgraduate'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], default='ug', max_length=20),
        ),
        migrations.AddField(
            model_name='courses',
            name='mode',
            field=models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('distance', 'Distance Education')], default='full-time', max_length=20),
        ),
        migrations.AddField(
            model_name='courses',
            name='schedule',
            field=models.CharField(blank=True, default='', help_text='E.g., June Intake, Academic Year 2025-26', max_length=100),
        ),
        migrations.AlterField(
            model_name='courses',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date when the course was created'),
        ),
    ]
