# Generated by Django 5.1.7 on 2025-04-12 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collages', '0005_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Contact number for admission inquiries', max_length=15)),
                ('email', models.EmailField(help_text='Contact email for admission inquiries', max_length=255)),
                ('name', models.CharField(help_text='Name of the applicant', max_length=100)),
                ('state', models.CharField(help_text='State of residence', max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='collages.courses')),
            ],
            options={
                'verbose_name': 'Admission',
                'verbose_name_plural': 'Admissions',
                'db_table': 'admissions',
                'ordering': ['-course__created_at'],
            },
        ),
    ]
