# Generated by Django 5.1.7 on 2025-04-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collages', '0006_admission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admission',
            options={},
        ),
        migrations.AddField(
            model_name='admission',
            name='pincode',
            field=models.CharField(default=1, help_text="Postal code of the applicant's address", max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admission',
            name='course',
            field=models.CharField(help_text='Name of the course for admission', max_length=100),
        ),
    ]
