# Generated by Django 5.1.7 on 2025-04-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collages', '0007_alter_admission_options_admission_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='message',
            field=models.TextField(default=1, help_text='Additional message or query from the applicant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admission',
            name='qualification',
            field=models.CharField(default=1, help_text='Highest qualification of the applicant', max_length=100),
            preserve_default=False,
        ),
    ]
