# Generated by Django 5.1.7 on 2025-04-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collages', '0008_admission_message_admission_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date when the admission inquiry was created', null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='is_viewed',
            field=models.BooleanField(default=False, help_text='Has the admission inquiry been viewed?'),
        ),
    ]
