# Generated by Django 5.1.7 on 2025-03-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_app', '0002_alter_university_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('established_year', models.PositiveIntegerField()),
                ('accreditation', models.CharField(blank=True, max_length=255, null=True)),
                ('university_affiliated', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('total_seats', models.PositiveIntegerField(default=0)),
                ('available_seats', models.PositiveIntegerField(default=0)),
                ('fee_structure', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='college_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
