# Generated by Django 5.1.7 on 2025-04-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_app', '0003_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
