# Generated by Django 5.1.7 on 2025-04-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_app', '0004_college_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
