# Generated by Django 5.1.7 on 2025-04-04 12:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_app', '0005_college_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='description',
        ),
        migrations.AddField(
            model_name='college',
            name='content',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='university',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
