# Generated by Django 5.1.7 on 2025-04-04 12:30

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission_app', '0006_remove_college_description_college_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
