# Generated by Django 5.1.7 on 2025-04-05 04:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission_app', '0007_alter_college_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
