# Generated by Django 5.1.7 on 2025-04-07 04:00

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission_app', '0008_alter_college_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
