# Generated by Django 5.1.7 on 2025-04-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_app', '0009_alter_college_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='fee_structure',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
